---
title: "Data Import"
output: github_document
---

```{r setup}
library(tidyverse)
library(readxl)
library(haven)
```

## Read in some data

Read in the litters dataset.

```{r }
litters_df = read_csv("./data/FAS_litters.csv")
litters_df = janitor :: clean_names(litters_df)
```

## Take a look at the data

Printing in the console
```{r}
litters_df
```

```{r}
head(litters_df)
tail(litters_df)
```

```{r}
skimr:: skim(litters_df)
```

## Options to read_cvs

check out `?read_csv()` for more information.

## Other file formats

Read in an excel file

```{r}
mlb_df = read_excel("./data/mlb11.xlsx", range = "A1:F7")
mlb_df
```

Read in a SAS file.
```{r}
pulse_df = read_sas("./data/public_pulse_data.sas7bdat")
pulse_df
```

## Comparsion with Base R

what about `read.csv` ...?
- - never!

```{r}
litters_base = read.csv("./data/FAS_litters.csv") #outdated
litters_readr = read_csv ("./data/FAS_litters.csv") #latest version of R read this

litters_base #more difficult to read
litters_readr
```

## Exporting data

Export the mlb sub-table.

```{r}
write_csv(mlb_df, "./data/mlb_subtable.csv")
```









